org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
flutter.enableV2Embedding=true
android.builtInKotlin=false
android.newDsl=false
android.suppressUnsupportedOptionWarnings=android.builtInKotlin,android.newDsl
